version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/outputs:/app/backend/outputs
      - ./backend/downloads:/app/backend/downloads
    environment:
      - PYTHONUNBUFFERED=1
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped